# the parameters of a run

# SPDX-License-Identifier: Apache-2.0

from datetime import datetime, timezone
import sys

class RunParams:
    def __init__(self):
        self._ts = datetime.now(timezone.utc)

    @property
    def parser_version(self):
        return sys.modules['spec_parser'].__version__
    
    @property
    def autogen_header(self):
        return f"Automatically generated by spec-parser v{self.parser_version} on {self._ts.isoformat()}"

# TODO: add more parameters, specified as command-line arguments
# - input dir
# - output dir for mkdocs
# - output file for RDF ontology
# - output file for JSON-LD schema
# - output file for JSON-LD context
# - maybe flags whether something might not be generated?
# - etc.
    
    @property
    def all_as_dict(self):
        return { k: getattr(self, k) for k in ("autogen_header", "parser_version") }

